### ISSUE TITLE
SC 29 October 2019 - Known agenda items

### ISSUE THREAD

**Issue by jude2018** [OpenWIS/openwis-documentation#560]
Per SC on 22 May - 

- [x] Review and agree strategic goals and metrics #554 

- [ ] Finalise updates to the Articles of Association #553 

- [ ] Finalise procurement approach for CI environment and licence-free OpenWIS 3x, for more info, see #557

**Comment by jude2018** [comment]
Decide goals #215 and #442

**Comment by jude2018** [comment]
Close as superseded by Dec 2019 SC meeting.  #553 and #557 in progress and will be part of SC agenda in March 2020.
